### ISSUE TITLE
Example on Fluxx's github page fails

### ISSUE THREAD

**Issue by garyrob** [zoofIO/flexx#24]
I tried to run the example code that appears on Fluxx's Github page. I put the code that appears there into the file test1.py:

    (py34)Gary-Robinsons-Retina-Macbook-Pro:flexx garyrob$ python test1.py
    Serving apps at http://localhost:49270/
    Traceback (most recent call last):
    File "test1.py", line 17, in <module>
        main = app.launch(Example)
    File "/Users/garyrob/anaconda/envs/py34/lib/python3.4/site-packages/flexx/app/proxy.py", line 387, in launch
        proxy = Proxy(cls.__name__, runtime, **runtime_kwargs)
    File "/Users/garyrob/anaconda/envs/py34/lib/python3.4/site-packages/flexx/app/proxy.py", line 451, in __init__
        self._launch_runtime(runtime, **runtime_kwargs)
    File "/Users/garyrob/anaconda/envs/py34/lib/python3.4/site-packages/flexx/app/proxy.py", line 500, in _launch_runtime
        runtime=runtime, **runtime_kwargs)
    File "/Users/garyrob/anaconda/envs/py34/lib/python3.4/site-packages/flexx/app/proxy.py", line 384, in launch
        return webruntime.launch(cls, runtime, **runtime_kwargs)
    File "/Users/garyrob/anaconda/envs/py34/lib/python3.4/site-packages/flexx/webruntime/__init__.py", line 111, in launch
        rt = Runtime(**kwargs)
    File "/Users/garyrob/anaconda/envs/py34/lib/python3.4/site-packages/flexx/webruntime/common.py", line 91, in __init__
        BaseRuntime.__init__(self, **kwargs)
    File "/Users/garyrob/anaconda/envs/py34/lib/python3.4/site-packages/flexx/webruntime/common.py", line 30, in __init__
        self._launch()
    File "/Users/garyrob/anaconda/envs/py34/lib/python3.4/site-packages/flexx/webruntime/xul.py", line 274, in _launch
        exe = self._get_app_exe(xul_exe, app_path)
    File "/Users/garyrob/anaconda/envs/py34/lib/python3.4/site-packages/flexx/webruntime/xul.py", line 455, in _get_app_exe
        self._osx_create_app(op.realpath(xul_exe), exe, title)
    File "/Users/garyrob/anaconda/envs/py34/lib/python3.4/site-packages/flexx/webruntime/xul.py", line 519, in _osx_create_app
        icon = Icon(self._kwargs['icon'])  # accepts ico/png/bmp
    File "/Users/garyrob/anaconda/envs/py34/lib/python3.4/site-packages/flexx/util/icon.py", line 269, in __init__
        self.read(filename)
    File "/Users/garyrob/anaconda/envs/py34/lib/python3.4/site-packages/flexx/util/icon.py", line 294, in read
        raise ValueError('Icon.read() needs a file name')
    ValueError: Icon.read() needs a file name

**Comment by almarklein** [comment]
Reproduced on osx. Thanks for reporting!

**Comment by almarklein** [comment]
Fixed in current master. Thanks again!
