### ISSUE TITLE
Improved stack tracing of errors happening at the python/JS boundary

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [zoofIO/flexx#270]
Running a piece of code of the form:

```
class Foo(ui.Widget):
    class Both:
        @event.prop
        def bar(self, val):
            return val
app.launch(Foo, properties=dict(bar=np.arange(3)))
app.start()

```

Will fail with an error that will do little to inform you of the line at which the problem originated; the ndarray will fail to serialize, and we are informed of that, but there is no feedback as to which property, or which invocation thereof, this problem appeared.

Is there a way to extend the tracability of errors like this? If so, it would be much appreciated.

**Comment by almarklein** [comment]
I get:
```
Traceback (most recent call last):
  File "<tmp 3>", line 8, in <module>
    app.launch(Foo, properties=dict(bar=np.arange(3)))
  File "d:\dev\pylib\flexx\flexx\app\funcs.py", line 378, in launch
    session = manager.create_session(name)
  File "d:\dev\pylib\flexx\flexx\app\session.py", line 148, in create_session
    app = cls(session=session, is_app=True, **properties)  # is_app marks it as main
  File "d:\dev\pylib\flexx\flexx\ui\_widget.py", line 117, in __init__
    Model.__init__(self, *init_args, **kwargs)
  File "d:\dev\pylib\flexx\flexx\app\model.py", line 410, in __init__
    super().__init__(_init_handlers=False, **kwargs)
  File "d:\dev\pylib\flexx\flexx\event\_hasevents.py", line 162, in __init__
    setattr(self, name, value)  # should raise error whith readonly
  File "d:\dev\pylib\flexx\flexx\app\model.py", line 505, in __setattr__
    event.HasEvents.__setattr__(self, name, value)
  File "d:\dev\pylib\flexx\flexx\event\_emitters.py", line 121, in __set__
    return instance._set_prop(self._name, value)
  File "d:\dev\pylib\flexx\flexx\app\model.py", line 540, in _set_prop
    txt = serializer.saves(value)
  File "d:\dev\pylib\flexx\flexx\app\clientcore.py", line 307, in saves
    return JSON.stringify(obj, _replacer)
  File "d:\dev\pylib\flexx\flexx\app\clientcore.py", line 295, in stringify
    return json.dumps(obj, default=replacer)
  File "C:\miniconda3\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\miniconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\miniconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "d:\dev\pylib\flexx\flexx\app\clientcore.py", line 330, in _replacer
    raise TypeError('Cannot serialize object to JSON: %r' % obj)
TypeError: Cannot serialize object to JSON: array([0, 1, 2])
```

So, the offending line is in there, all the way at the top. I agree that the traceback is rather ... big

**Comment by almarklein** [comment]
```py
from flexx import app, ui, event
import numpy as np
class Foo(ui.Widget):
    class Both:
        @event.prop
        def bar(self, val):
            return val

def test():
    m.bar = np.arange(3)

m = app.launch(Foo)
app.call_later(1, test)
app.start()
```

Gives me:

```
[E 12:14:11 flexx.app] Cannot serialize object to JSON: array([0, 1, 2])
  File "<tmp 3>", line 10, in test
    m.bar = np.arange(3)
  File "d:\dev\pylib\flexx\flexx\app\model.py", line 505, in __setattr__
    event.HasEvents.__setattr__(self, name, value)
  File "d:\dev\pylib\flexx\flexx\event\_emitters.py", line 121, in __set__
    return instance._set_prop(self._name, value)
  File "d:\dev\pylib\flexx\flexx\app\model.py", line 540, in _set_prop
    txt = serializer.saves(value)
  File "d:\dev\pylib\flexx\flexx\app\clientcore.py", line 307, in saves
    return JSON.stringify(obj, _replacer)
  File "d:\dev\pylib\flexx\flexx\app\clientcore.py", line 295, in stringify
    return json.dumps(obj, default=replacer)
  File "C:\miniconda3\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\miniconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\miniconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "d:\dev\pylib\flexx\flexx\app\clientcore.py", line 330, in _replacer
    raise TypeError('Cannot serialize object to JSON: %r' % obj)
```

Which is a bit shorter.

**Comment by almarklein** [comment]
Although I can see it becoming much shorter by capturing in the serializer and raising a new error.
