### ISSUE TITLE
No flexx/ui/_iframe.py 

### ISSUE THREAD

**Issue by pya** [zoofIO/flexx#35]
The example `hello_world.py` fails:

```
Traceback (most recent call last):
  File "hello_world.py", line 6, in <module>
    from flexx import app, ui
  File "/Users/mike/Dev/flexx/flexx/ui/__init__.py", line 90, in <module>
    from ._iframe import IFrame
Traceback (most recent call last):
  File "hello_world.py", line 6, in <module>
    from flexx import app, ui
  File "/Users/mike/Dev/flexx/flexx/ui/__init__.py", line 90, in <module>
    from ._iframe import IFrame
```
Looks like `lexx/ui/_iframe.py` has not been checked in yet. Commenting out the line `from ._iframe import IFrame` fixes the problem.

**Comment by almarklein** [comment]
Doh! I forgot to `git add` it, classic mistake. I really need to setup CI soon. Anyway, I just pushed the file up. Thanks!
