### ISSUE TITLE
error `object does not have a signal` trying `find_prime.py`

### ISSUE THREAD

**Issue by stonebig** [zoofIO/flexx#42]
on today trunk, trying `find_prime.py` gives this to me:
````
Traceback (most recent call last):
  File "D:/WinPythonQt5/basedir34/build/winpython-3.4.3.amd64/notebooks/find_prime.py", line 60, in <module>
    finder = app.launch(PrimeFinder, 'nodejs')  # can also use Firefox or Chrome
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\flexx\app\funcs.py", line 185, in launch
    session = manager.create_session(cls.__name__)
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\flexx\app\session.py", line 85, in create_session
    app = cls(session=session, container='body')
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\flexx\app\model.py", line 244, in __init__
    react.HasSignals.__init__(self, **kwargs)
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\flexx\react\hassignals.py", line 87, in __init__
    raise ValueError('Object does not have a signal %r' % name)
ValueError: Object does not have a signal 'container'
>>> 
````

**Comment by almarklein** [comment]
Thanks for reporting!
