### ISSUE TITLE
Python 3.5 compatibility broken

### ISSUE THREAD

**Issue by HittingSmoke** [zoofIO/flexx#48]
When using Flexx with Python 3.5:

```python
$ python ../signage/demo.py 
Traceback (most recent call last):
  File "../signage/demo.py", line 1, in <module>
    from flexx import app, ui, react
  File "/home/chris/signage35/lib/python3.5/site-packages/flexx/app/__init__.py", line 61, in <module>
    from .proxy import run, start, stop, init_notebook, call_later
  File "/home/chris/signage35/lib/python3.5/site-packages/flexx/app/proxy.py", line 17, in <module>
    from .clientcode import clientCode, Exporter # global client code
  File "/home/chris/signage35/lib/python3.5/site-packages/flexx/app/clientcode.py", line 48, in <module>
    @py2js
  File "/home/chris/signage35/lib/python3.5/site-packages/flexx/pyscript/functions.py", line 73, in py2js
    p = Parser(pycode, **parser_options)
  File "/home/chris/signage35/lib/python3.5/site-packages/flexx/pyscript/parser0.py", line 190, in __init__
    self._parts = self.parse(self._root)
  File "/home/chris/signage35/lib/python3.5/site-packages/flexx/pyscript/parser0.py", line 340, in parse
    res = parse_func(node)
  File "/home/chris/signage35/lib/python3.5/site-packages/flexx/pyscript/parser1.py", line 553, in parse_Module
    code += self.parse(child)
  File "/home/chris/signage35/lib/python3.5/site-packages/flexx/pyscript/parser0.py", line 340, in parse
    res = parse_func(node)
  File "/home/chris/signage35/lib/python3.5/site-packages/flexx/pyscript/parser2.py", line 770, in parse_ClassDef
    if node.keywords or node.starargs or node.kwargs:
AttributeError: 'ClassDef' object has no attribute 'starargs'
```

See [this issue](https://github.com/alecthomas/importmagic/issues/25) for details on the backwards-compatibility breakage in Python 3.5 with an attached patch they used to fix it.

**Comment by almarklein** [comment]
Yes, I am aware of this. I'm working on the PyScript ast stuff now. Maybe we'll use a differen ast parser. If not, that link is going to be helpful :)  Thanks

**Comment by almarklein** [comment]
Fixed! Travis now also tests py 35 and pypy3.

**Comment by almarklein** [comment]
#51

**Comment by kootenpv** [comment]
It would be great if this could be released.

**Comment by almarklein** [comment]
This is in v0.2
